#' @title Determine size of file header
#'
#' @description Returns the size in bytes of an LPJmL file header based on
#' a header list object read by readHeader() or generated by newHeader()
#'
#' @param header Header list object as returned by readHeader() or newHeader()
#'
#' @return Integer value giving the size of the header in bytes. This can be used when seeking in the file.
#'
#' @examples
#' \dontrun{
#' header <- readHeader("filename.clm")
#' size <- headerSize(header)
#' # open file for reading
#' fp <- file("filename.clm", "rb")
#' # skip over file header
#' seek(fp, size)
#' # add code to read data from file
#' }
#' @seealso [readHeader()] for reading a header from an LPJmL file, [newHeader()] fore creating a header from scratch.
#' @export
headerSize <- function(header) {
  if(!is.list(header)) {
    stop("Header must be a list")
  }
  if(!("name" %in% names(header)) || !("version" %in% names(header$header))) {
    stop("Header list must contain a 'name' and a 'header' element.")
  }
  return(nchar(header$name)+switch(as.integer(header$header["version"]), 7, 9, 11)*4)
}
