# testthat snapshots are machine-generated regression tests that
# have to be preserved exactly as they are
exclude: '^tests/testthat/_snaps/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: fix-byte-order-marker
    -   id: check-added-large-files
        args: ['--maxkb=100']
    -   id: mixed-line-ending

-   repo: https://github.com/lorenzwalthert/precommit
    rev: 7910e0323d7213f34275a7a562b9ef0fde8ce1b9  # frozen: v0.4.2
    hooks:
    -   id: parsable-R
    -   id: deps-in-desc
        args: [--allow_private_imports]
    -   id: no-browser-statement
    -   id: no-debug-statement
    -   id: readme-rmd-rendered
    -   id: use-tidy-description
ci:
    autoupdate_schedule: quarterly
